# Uses default credentials
version: '3.1'

services:
  db:
    image: mysql:5.5.42
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: tabledata
